---
- name: Add repository
  apt_repository:
    repo: ppa:martin-frost/thoughtbot-rcm
    filename: thoughtbot
    state: present
  become: yes
  
- name: Install package
  apt:
    name: rcm
    update_cache: yes
    state: present
  become: yes
