---
- name: Install packages
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - emacs
    - fonts-powerline
    - git
    - htop
    - libmysqlclient-dev
    - libncurses5-dev
    - libpcre3-dev
    - libpq-dev
    - libsqlite3-dev
    - pkg-config
    - postgresql
    - silversearcher-ag
    - tmux
    - tree
    - vim
    - xclip
    - zsh
  tags:
    - common

