---
- name: docker - Add repository key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
  tags:
    - docker

- name: docker - Add repository
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
  tags:
    - docker

- name: docker - Install package
  apt:
    pkg: docker-engine
    update_cache: yes
  tags:
    - docker

- name: docker - Create group
  group:
    name: docker
