---
- name: Add key
  apt_key:
    id: 0C49F3730359A14518585931BC711F9BA15703C6
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
  become: yes

- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64,arm64] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse"
    filename: "mongodb-org"
    state: present
  become: yes

- name: Install package
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  become: yes

- name: Start service
  service:
    name: mongod
    state: started
    enabled: yes
  become: yes
